### ISSUE TITLE
UI Kit: Accordions

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/ui-kit-base-theme#1]
**As a content author
I want to be able to use accordions in my content
So users can easily find only the content they need.**

https://gov-au-ui-kit.apps.staging.digital.gov.au/section-accordions.html

---

I can't see that there are any elements within Drupal's standard markup that we'd want to apply accordion styles to, I suspect it's just within the content.  As a result, this issue it probably a freebe as we get it out of the box with the UI Kit, we'd just need to test that applying the markup/classes within a markup field produces the desired outcome with no style conflicts etc.

**Comment by rujiali** [comment]
Agree with the approach.

**Comment by rujiali** [comment]
Tested with full HTML input format in sample node text area. The according is working when input with the sample html code.
![screen shot 2016-12-13 at 10 27 53 am](https://cloud.githubusercontent.com/assets/3487406/21121176/08512bd0-c11f-11e6-8335-4c0fb4ef40d2.png)

**Comment by Feng-Shui** [comment]
@rujiali Are there be expand/collapse indicators as per the documentation? https://gov-au-ui-kit.apps.staging.digital.gov.au/section-accordions.html#guide-accordions-2-controls-accordion

**Comment by rujiali** [comment]
@Feng-Shui yep, can use 'open' and 'closed' in the tag per `<details class="accordion--controls" data-label="accordion-controls-example" 
  aria-expanded="false" closed>` to indicate the status.

**Comment by DJMyles** [comment]
@Feng-Shui tested. These will form the basis of our enabler groups and I had them configured within dhs_blocks to work on the service content type pages.

Confirmed they are working including expand / collapse

**Comment by Feng-Shui** [comment]
Excellent, closing this one.
