### ISSUE TITLE
Drupal: starterkit

### ISSUE THREAD

**Issue by rujiali** [govCMS/ui-kit-base-theme#10]
**As a developer
I want to be able to create a sub-theme from a template and add my custom styles and layout to it.**

---

We need to create a STARTERKIT folder in uikit_base theme similar to the Zen theme. So that user can simply copy the STARTERKIT in the theme root and rename the variables using their own theme name. 
_Proposed tasks:_
1. Clean up template.php
2. Remove all tpl files
3. Add base theme settings in info.txt file
4. Add README file
5. Modify styles.scss and info.txt to reference the uikit library to the base theme (After talking to @Feng-Shui )
6. Modify gulp build task

**Comment by Feng-Shui** [comment]
Yeah, we're going to need to make it easier for the end user to do this.  Suggest that we extract a starter kit theme from the sub-themes that we make off the base theme in the next 8-10 weeks?

**Comment by rujiali** [comment]
As we need to start to build the site in govCMS in next sprint, we will need to make the STARTERKIT asap so that the work can be shipped in our new subtheme. And yes, we will make off the STARTERKIT from the base theme. I will work with @dlm78 today on it as the top priority.

**Comment by dlm78** [comment]
@rujiali STARTERKIT ready to test in branch of the same name.

**Comment by DJMyles** [comment]
Merged into master
