### ISSUE TITLE
UI Kit: Link styles

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/ui-kit-base-theme#11]
**As a site user
I want accessibly and visually obvious links
So I can identify links easily.**

https://gov-au-ui-kit.apps.staging.digital.gov.au/section-link-styles.html

---

Basic link styles from the UI Toolkit should just drop in and work. There are a few considerations we need to make though.

The [External Links](https://www.drupal.org/project/extlink) module is a pretty common way of providing functionality to visually identify external links and it would be nice to provide out of the box support for it in the theme.  It's standard selector to denote external links is `span.ext`.  Thoughts on extending that selector to include UI Kit's external link styling?  The module's selector is pretty light, so I don't think we need to strip it (and it also provides `span.mailto` which the UI Kit doesn't support).

"Read more" links on Views and Node teasers should be implemented using the [See more](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-link-styles.html#guide-link-styles-2-see-more-link) implementation.

**Comment by DJMyles** [comment]
So in regards to links in navs etc, we need to be able to apply the UI Kit classes to various Drupal equivalents. I thought I had a solution to this but it's actually harder than first thought. Specifically:

- active-trail -> is-active
- active -> is-current

The l() theme_links() and theme_menu_link() functions play a part in this but it's messy.

cc @Feng-Shui

**Comment by rujiali** [comment]
My gut feeling is to use [THEME_link](https://api.drupal.org/api/drupal/includes!theme.inc/function/theme_link/7.x) and add the class to the `class` array.

**Comment by Feng-Shui** [comment]
Yeah, that may do it.

Interestingly, I'd never read through all the code for l(), is only runs links through that theme function if specifically requested by a theme or module: https://api.drupal.org/api/drupal/includes%21common.inc/function/l/7.x

Would explain why sometimes you don't get a theme function listed when using tools like devel themer.

**Comment by rujiali** [comment]
**Basic links**
Working out of box
**Navigation menu links**
Used theme function to add is-active class etc
**View more**
Added class in views-more.tpl.php which covers the teaser/compact etc node display mode and the Views
**External links**
1. Wysiwyg supports adding rel in content area.
2. Link field supports adding rel and conditions.
3. Menu links block is a blocker. Can't detect if the link is an external link without custom JS or extlink module.
4. extlink is not in govCMS SaaS. 
5. We can either alter the JS in extlink to add rel="external".
6. Or style the span from extlink using the UI KIT style.

Suggestions? @Feng-Shui

**Comment by Feng-Shui** [comment]
3: Let's not get hung up on that, happy to let that one go.
6: That's my preference, although this is not an MVP requirement, so happy for us to sort that one if you'd prefer (suggest /sass/modules/_extlinks.scss)

**Comment by Feng-Shui** [comment]
Merged, thanks @rujiali
