### ISSUE TITLE
UI Kit: List styles

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/ui-kit-base-theme#13]
**As a site editor
I want a range of list styles
So I can make collections of similar content more usable and discoverable.**

https://gov-au-ui-kit.apps.staging.digital.gov.au/section-list-styles.html

---

The DTAs list styles are for the presentation of lists of articles and more complex content rather than being simple bulleted lists.

These should just drop in without any issue, but I think we should see how they play with Views specifically.  Are we able to add the list classes to Views (via the Views admin UI) and have the lists "just work"?  If not, it might be worth looking at developing unique Views styles to output these correctly - although that may require a module?

**Comment by DJMyles** [comment]
<img width="716" alt="screen shot 2016-12-15 at 9 44 46 am" src="https://cloud.githubusercontent.com/assets/14192426/21204353/2d52f3d6-c2ab-11e6-8ff6-ac7f3452e8c2.png">

Hey @Feng-Shui I'd previously mucked around this with news stories and can confirm that the various list patterns work out of the box with views which has enough controls and flexibility to cater for the various patterns. Screenshot above reflects a basic ` .list-horizontal ` with basic image. Some of the elements we don't use however I've included them to fully display the pattern.

**Comment by DJMyles** [comment]
There seems to be an issue with the grid?? I think at the moment in that the main content area seems abnormally narrow. Not sure what is gong on there but I suspect its simply because we haven't really done any grid config at the moment.

**Comment by rujiali** [comment]
@DJMyles Not sure if it is the case when you have nothing (no blocks) configured in the sidebar region. The sidebar (4 of 16) will not appear but the main will remain 12 of 16 grids ?

**Comment by DJMyles** [comment]
@rujiali I suspect that could be the case. Maybe the logic in page.tpl.php needs to be something like:

if no sidebar -> 16 of 16 columns for main
if sidebar left -> float left (and use 4 cols) -> main = 12 cols
if sidebar right -> float right (and use 4 cols) -> main = 12 cols

The class attached to the ` <main> ` element (as per toolkit) determines if it is left or right ( `.siderbar-has-controls`)

I wonder if there is also a business a case where both left and right sidebars might be used at once, in which case it would be main -> 8 cols and each respective sidebar 4 cols.

cc @Feng-Shui

**Comment by rujiali** [comment]
Let's continue the conversation in the grid issue. 

As for the list styles, have you got chance to check how list style behaves in other regions? @DJMyles

**Comment by DJMyles** [comment]
@rujiali in terms of header, footer and sidebar?

**Comment by rujiali** [comment]
yes @DJMyles , the UI KIT may have `main > li { xxxxx:xxxxx}`, which will make the styles not available in other region.

**Comment by DJMyles** [comment]
I've created a new state of ` blocked ` and put this into that category until we sort out https://github.com/govCMS/ui-kit-base-theme/issues/8 as it is going to be needed to properly test this within nested grids and different regions with different column counts etc.

At the moment we are using the gov.au toolkit grid defaults which may / may not be fit for purpose or achieve our business requirements. 

Personally i really dislike the fact that the grid will only ever use 12 of 16 columns for the main content area even if navigation is not present. 

Thoughts @Feng-Shui @rujiali

**Comment by Feng-Shui** [comment]
I think we need to bring everyone in to this discussion.  Suggest that we ( @mgdhs @dlm78 @rujiali @DJMyles ) jump on a call to talk this one through?

**Comment by rujiali** [comment]
I guess we move to #8 for the conversation ?

**Comment by DJMyles** [comment]
@Feng-Shui yeah lets have a phone convo about this one and more broadly - grid.

Also some interesting discussion here: https://github.com/AusDTO/gov-au-ui-kit/issues/412

A very simple alt grid solution in there as well.

**Comment by Feng-Shui** [comment]
@DJMyles what's the relationship with the grid that's blocking this?  Is it the ability to layout content within templates?

**Comment by DJMyles** [comment]
@Feng-Shui it was a while ago so not sure but hasn't this issue been superceded by https://github.com/govCMS/ui-kit-base-theme/issues/33 now?

**Comment by Feng-Shui** [comment]
The grid component yeah, there's still more work to do on these though, waiting for Josh to take a look at some changes to the horizontal list PR.  Once we've got a baseline for these, this issue will be the building out of the rest of the list styles as DS templates using that horizontal one as an example.

**Comment by Feng-Shui** [comment]
Horizontal list has been implemented as a DS layout #33 and #37 

I'll continue in this vein to implement the remaining styles.

**Comment by DJMyles** [comment]
@Feng-Shui as a side note, the issue with the wrapping again came down to that line length issue we have previously discussed. Extending the 100% content class to the layouts will alleviate this issue.

**Comment by DJMyles** [comment]
<img width="890" alt="screen shot 2017-01-13 at 11 10 06 am" src="https://cloud.githubusercontent.com/assets/14192426/21913497/e2a05fa8-d980-11e6-989b-187579c519ef.png">

horizontal list item with image with the `.content-full-width` selector applied compared with the screenshot further above in this issue.

**Comment by Feng-Shui** [comment]
Closing this as it has been merged in, any issues can be raised as new issues :)
