### ISSUE TITLE
Undefined variable: sidebar_position_class

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/ui-kit-base-theme#14]
Following the sidebar commit, we've got:

`Notice: Undefined variable: sidebar_position_class in include() (line 55 of /var/www/dhs.local/docroot/sites/all/themes/ui-kit-base-theme/templates/page.tpl.php).`

Fixing this presents the opportunity to clean up another annoyance too:

`<main id="page" role="main" class="main <?php print $sidebar_position_class; ?>">`

This ins't create when `$sidebar_position_class` is undefined (apart from the notice - theme engine obviously doesn't create empty vars) because the resulting markup is:

`<main ... class="main ">`

That space with the class attribute hurts me deep inside.

Suggest that we create a new variable in `template.php` to replace `$sidebar_position_class`:

```php
/**
 * Implements THEME_preprocess_page().
 */
function uikit_base_preprocess_page(&$variables) {  
  // Position sidebar based on theme settings
  $variables['sidebar_position_class'] = '';
  if (theme_get_setting('sidebar_position') == 'left') {
    $variables['sidebar_position_class'] = 'sidebar-has-controls';
  }
}
```

Becomes:

```php
/**
 * Implements THEME_preprocess_page().
 */
function uikit_base_preprocess_page(&$variables) {
  // Get classes for <main> together
  $variables['main_classes'] = array('main');
  // Position sidebar based on theme settings
  if (theme_get_setting('sidebar_position') == 'left') {
    $variables['main_classes'][] = 'sidebar-has-controls';
  }
  $variables['main_classes'] = implode(' ', $variables['main_classes']);
}
```

`<main id="page" role="main" class="<?php print $main_classes; ?>">`

I'll put up a PR if we're happy with this.

**Comment by rujiali** [comment]
Regardless what I posted before, the default class should be `main`, and add `sidebar-has-controls` when need to. Agreed with solution.

**Comment by rujiali** [comment]
Submitted PR #15 @Feng-Shui

**Comment by Feng-Shui** [comment]
Thanks for sorting this one 👍
