### ISSUE TITLE
Module: Workbench

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/ui-kit-base-theme#16]
The Workbench module's node status and controls that appear when a user is logged and has editing permission look crap alongside the UI Kit styles (see attached screenshot).  Given this is part of govCMS core, and it visible on normal content pages for auth users, we need to update the styles.

The styling is applied to `div.workbench-info-block` so it should be easy to override.  Suggest that we use the `.callout--info` style for this element, thoughts?

Also, thoughts on creating a sass folder `/sass/modules/_modulename.scss` for customisations for specific modules?  Would make it easier to keep track of module specific styling and remove it if modules were ever removed from the distro.

<img width="775" alt="screen shot 2016-12-15 at 9 03 03 am" src="https://cloud.githubusercontent.com/assets/758574/21203239/bcf14d0e-c2a5-11e6-99b5-8dcc926eab2c.png">

**Comment by DJMyles** [comment]
I agree with both approaches in terms of class and sass structure. If there are no objections I'll sort this one out.

cc @Feng-Shui

**Comment by rujiali** [comment]
Agree with the solution. Feel free to start @DJMyles .
