### ISSUE TITLE
UI Kit: Navigation

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/ui-kit-base-theme#19]
**As a user
I want various levels of navigation
So I can understand where I am, where I have been and I they can go.**

https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html

---

# Menus

## Global and Site navigation

The UI Kit's [Global navigation](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-01-global-navigation) is described as providing ` an additional navigation level above the site navigation.`

The Kit's [Site navigation](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-02-site-navigation) is describe as providing `site navigation to help the user to navigate between main sections.`  It sounds like Drupal's `Main menu` is in rough alignment with the purpose of the `Site navigation`.

## Local navigation

The Kit's [Local navigation](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-03-local-navigation) is described as providing `local navigation to help the user to navigate within the current section.`.

## How this would relate to Drupal

It seems to me that the way to implement `Site navigation` and `Local navigation` in Drupal would to be a single menu that covered the whole site.  Show the top level as the `Site navigation`, and then use the `Menu block` module to show the children of the active `Site navigation` item in a block as `Local navigation`.  Another approach would be multiple menus, but the result would be the same.

## govCMS implementation

govCMS ships with a `Main menu` that only contains 1 level, and then uses Superfish to provide drop downs if that menu grows.   It also implements a menu block showing levels 2 & 3 of the `Main menu` as per the above proposed implementation (this block is placed in the sidebar).

## Propose implementation

Suggest that we

1. Assume that `Site navigation` is the top level of Drupal's `Main menu`
1. Assume that `Local navigation` will be provided using the `Menu block` module, but NOT assume that it would be a single block showing child links of the `Main menu`.
1. Given the above, we style any `Menu block` in a sidebar as `Local navigation` menu. `Or, do we style ANY Menu block as a Local navigation menu?`

I'm not sure what we do with `Global navigation` as I don't see a use for it in our site at the moment - @DJMyles with the exception of our top level audience links (Business, Corporate etc). Thoughts on this level of nav anyone?

# Content links

UI Kit refers to the functionality provided by [TOC filter](https://www.drupal.org/project/toc_filter) as [Content links](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-04-contents-links).  We should be able to implement `theme_toc_filter()` to match the Kits markup.  If this means that we aren't using any of the module's CSS, we should strip it.

# [Tab navigation](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-05-accessibility)

This should just work out of the box?

# [Breadcrumbs](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-07-breadcrumbs)

@DJMyles @rujiali you guys have both worked on this, yeah?  Do we already have code to match the Kit's markup?

# [Skip links](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-10-skip-links)

Drupal already has a `Skip to content` link, but does not have a `Skip to section navigation` as per the Kit.  We need to:

1. See if we can get the second skip to nav link in
1. Update the styling of the links

**Comment by Feng-Shui** [comment]
This is a pretty massive issue, but I've kept it as a single issue because parts of it are already implemented, I think.  Happy to decompose this into smaller issues you guys prefer.

**Comment by DJMyles** [comment]
@Feng-Shui I def see ` global navigation ` as equivilant to our views (corp, bus, cus, comm, minister etc)

Can confirm tab navigation already works out of the box as I've tested them for enabler groups.

Breadcrumbs have already been processed within the template to inherit correct classes and structure.

**Comment by Feng-Shui** [comment]
Perhaps a menu block placed in the site header picks up the `Global navigation` styles?

**Comment by DJMyles** [comment]
<img width="1214" alt="screen shot 2016-12-16 at 8 40 45 am" src="https://cloud.githubusercontent.com/assets/14192426/21243088/62bb5c14-c36b-11e6-855c-06d0c21b107e.png">

**Comment by DJMyles** [comment]
@Feng-Shui the issue with the global navigation style I found is that it is a dark background and clashes with the white themed header section. It never looked right.

**Comment by rujiali** [comment]
I don't see the global navigation fit in Drupal well. Do we need another region before the header to place the global navigation? We don't have this scenario in our case.

**Comment by Feng-Shui** [comment]
I think we will need another region, because targeting a menu within the current header region for styling will currently pick up the site nav menu (main menu).  Maybe the new region is called `Global nav` to indicate it's purpose?

**Comment by rujiali** [comment]
Agreed with the new region.

**Comment by Chris820** [comment]
Please be careful if considering locking things down to a single massive menu structure.

One menu for all the things is fine and dandy for small to medium sites. 
But we used to run a config like that our our Departmental website. Thousands of menu items. And quite often ran into memory issues.
In particular: The ContextUI would be non-responsive. Contexts couldn't be edited.
And we would also frequently get these moments where temporary://files couldn't be copied (something to do with the GlusterFS) so minified styles and scripts wouldn't load.

We didn't want to just keep throwing server resources at the problem. So eventually split our site up into multiple smaller menus. 
Hindsight now shows that using a Taxonomy with Views may have been a better option as a navigation system for a massive site (but is very time consuming to retrofit).

**Comment by Feng-Shui** [comment]
The proposed solution wouldn't be tied to a single big menu, if we were styling the menus based on where menu blocks were placed, you could have multiple small menus or one large menu as required.

**Comment by DJMyles** [comment]
This issue probably needs more discussion or split up into more manageable sub-issues. Thoughts?

**Comment by klepas** [comment]
Just a note that I added some further context info behind the global navigation in its ticket: https://github.com/govCMS/ui-kit-base-theme/issues/30#issuecomment-268434352

> 1. Assume that Site navigation is the top level of Drupal's Main menu
 
+1

> Assume that Local navigation will be provided using the Menu block module, but NOT assume that it would be a single block showing child links of the Main menu.

+1, beyond the first item in the local nav, there shouldn’t be any duplication between the two nav, eg. https://www.dta.gov.au/standard/

**Comment by Feng-Shui** [comment]
Global navigation has been removed from the latest version of the guide, as @rujiali didn't have a use for it, and we may not, going to suggest this is a sub-theme requirement.  @rujiali I'm going to remove `feature/global-navigation`, any objections?

**Comment by rujiali** [comment]
Please go ahead remove the branch. Thanks @Feng-Shui

**Comment by Podgkin** [comment]
@Feng-Shui  That description "where I have been and I they can go."
