### ISSUE TITLE
UI Kit: Alerts/message boxes

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/ui-kit-base-theme#2]
**As a website user
I want a consistent and meaningful set of message alert styles
So I can easily see specific changes in site status.**

https://gov-au-ui-kit.apps.staging.digital.gov.au/section-colours.html#guide-colours-2-contextual-colours-palette

---

The accessible colour combinations on the above page provide a good starting point for Drupal's message styles (and potentially page help).

- `.status` = `success-green on light-green`
- `.warning` = `non-black on light-yellow`
- `.error` = `error-red on light-red`

If we want to look at styling the page help using `non-black on light-blue` would prob be a good option.

It might be worth stripping out [system.messages.css](https://api.drupal.org/api/drupal/modules!system!system.messages.css/7.x) using [hook_css_alter](https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_css_alter/7.x) so we don't have to battle with the default styling.  If we did this, we'd need to make sure that we dropped in appropriate margins on pages where multiple message types (multiple of the same type, and multiple different types) appeared.

**Comment by Feng-Shui** [comment]
Just thinking, that it might be worth implementing a `.info` using `non-black on light-blue`.

**Comment by rujiali** [comment]
Agreed with the colour matching. 
system.message.css is currently removed from the info file. I'm using THEME_status_message to add the classes. Currently it is using '[index-links](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html)' style. I'm happy to rewrite it using the colour class. And yes we need to set up the margins, which will be our custom style. Are we happy about it?

**Comment by Feng-Shui** [comment]
What are your thoughts on importing the colour classes/variables into the message levels within the Drupal sass:

```
.status {
  background-color: $light-green;
  color: $success-colour;
}
```

As opposed to adding extra classes to the message markup itself?

I think there are benefits to handling that as the sass level, as that allows you to use those single semantic classes throughout the rest of the site?  Thoughts?

Ping @DJMyles @dlm78

**Comment by DJMyles** [comment]
Yeah I'd prefer to import it for use in messages as a variable within the SASS.

These won't be limited to just $messages though. There are content applications of these patterns so we need to ensure publishers have access to whatever style we come up with for exposure to end users (not just admin).

**Comment by DJMyles** [comment]
So I'm thinking we do this like:

a basic `.alert` class which defines the basic container (no colors)
individual `.success .info .warning` classes which defines the coloring (border, background etc) along with an icon if applicable
the above coloring selectors should draw from defined color variables

so we might have:

`<div class="alert info"><p>foobar</p></div>`

What do you guys think?

**Comment by Feng-Shui** [comment]
No issues.  Although I'd prefer `.message` over `.alert` as they are already `messages` in Drupal so it's consistent with the existing terminology.

Just as an aside, we also have to cater for links within the messages, not sure what the default link styling looks like when combined with the various message colours.

**Comment by DJMyles** [comment]
I'm inclined to keep the color very subtle (only a distinguishing red, green, blue on a border) and keep the font color default, that way the anchor color styling remains viable. It also retains the principles of simplicity of the DTO design.

**Comment by dlm78** [comment]
Sorry for the silence. Been tweaking the theme/prototype package.

The theme has access to all the UI-kit goodies including variables and mixins so yes I agree that were available we use the UI-kit ones.

At the sub-theme level, it may be prudent to redeclare them so that sub-theme variables are assigned from UI-kit ones. For example:

$my-theme-failure-colour = 'red' // if not used by UI-kit
$my-theme-success-colour = $success-colour // if it is

**Comment by Feng-Shui** [comment]
Cool, I think there's enough here to progress this one, I've moved it into `Todo`.

**Comment by DJMyles** [comment]
See feature/message-styles

<img width="643" alt="screen shot 2016-12-13 at 3 35 25 pm" src="https://cloud.githubusercontent.com/assets/14192426/21127944/da5426a2-c14a-11e6-9b29-04aeafb4fec4.png">
<img width="841" alt="screen shot 2016-12-13 at 3 33 55 pm" src="https://cloud.githubusercontent.com/assets/14192426/21127947/e287fd4e-c14a-11e6-9dfe-e11b30d6541f.png">

**Comment by dlm78** [comment]
The UI-kit already caters for callouts and warnings at https://gov-au-ui-kit.apps.staging.digital.gov.au/section-typography.html#guide-typography-7-callouts-warnings

**Comment by DJMyles** [comment]
Well there ya go...

@Feng-Shui I thought issues were only being raised for stuff that was missing? My bad for not checking and assuming I guess :(

**Comment by rujiali** [comment]
The style is not applied to Drupal messages, reopen the issue.
The UI KIT callouts and warnings only contains the style for warning (red), other message types are not define in the UI KIT. We still need to add our custom styles to define it. Or we need to contact DTA to add those styles. Thoughts ? @Feng-Shui @DJMyles

**Comment by DJMyles** [comment]
The UI Kit is light on in their callout styles so what I propose to do is contribute back directly to the toolkit and add support for callouts that reflect the other message states. This will be a good opportunity to contribute to the toolkit. I'll then update the template so that messages also get the callout class.

**Comment by DJMyles** [comment]
ready for review. If we're happy I'll approach the DTA guys and ask them how they want to go about me popping a PR into their own repo with the styles.

**Comment by DJMyles** [comment]
Updated
