### ISSUE TITLE
UI Kit: Footer menus

### ISSUE THREAD

**Issue by DJMyles** [govCMS/ui-kit-base-theme#22]
DTA kit provides footer markup as per the following:

```
 <footer role="contentinfo">
  <div class="wrapper">
    <section class="footer-top">
      <nav>
        <ul>
          <li><h2>Title header</h2></li>
          <li><a href="#">This is a footer link</a></li>
          <li><a href="#">This is a footer link</a></li>
        </ul>
        <ul>
          <li><h2>Title header</h2></li>
          <li><a href="#">This is a footer link</a></li>
          <li><a href="#">This is a footer link</a></li>
        </ul>
        <ul>
          <li><h2>Title header</h2></li>
          <li><a href="#">This is a footer link</a></li>
          <li><a href="#">This is a footer link</a></li>
        </ul>
        <ul>
          <li><h2>Title header</h2></li>
          <li><a href="#">This is a footer link</a></li>
          <li><a href="#">This is a footer link</a></li>
        </ul>
      </nav>
    </section>
    <section>
      <div class="footer-logo">
        <img alt="Australian Government Coat of Arms" 
          src="/latest/img/coat-of-arms.png">
      </div>
      <div class="footer-links">
        <nav>
          <ul>
            <li><a href="#">Example global link</a></li>
            <li><a href="#">Example global link</a></li>
          </ul>
        </nav>
        <p>&copy; Commonwealth of Australia <br>
        <a href="https://github.com/AusDTO/gov-au-ui-kit/blob/master/LICENSE.md"
           rel="external license">Licensed under the MIT License.</a></p>
      </div>
    </section>
    </div>
  </footer> 
```
And states:

> This framework uses CSS Flexboxes to manage columns. It provides:
> 
> lists of links arranged horizontally
> 2 columns for $mobile and $tablet breakpoint
> 4 columns for $desktop breakpoint.

Personally I don't think including the menu / block title as the first `<li>` element of the `<ul>` is semantically correct. It also makes theming and styling of the menus difficult.

I propose creating a footer_top region for menu blocks only (as per the toolkit) and splitting content up into each as per the markup, and instead of targeting the `<ul>` with the grid columns we add a class to `block--footer-top.tpl.php` and use that instead, which will encompass the menu + the heading with the correct structure which should be something like:

```
<h2>Title header</h2>
 <ul>
      <li><a href="#">This is a footer link</a></li>
      <li><a href="#">This is a footer link</a></li>
 </ul>
```

<img width="1258" alt="screen shot 2016-12-16 at 11 10 57 am" src="https://cloud.githubusercontent.com/assets/14192426/21246997/5bf194ce-c380-11e6-9acd-d529be6734e2.png">

**Comment by rujiali** [comment]
Agreed using the block--[region].tpl.php and moving the title out of the li. 
Not sure about the new region for menu blocks. As [https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-09-footer-navigation](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-09-footer-navigation) has divided the footer into two parts (section class="footer-top" and the rest as a section). So I would stay with the UI KIT layout in the footer.

**Comment by klepas** [comment]
Hey, wanted to say thanks for raising this with us upstream. (:

We’ve fixed this, and amended the html examples. It’s sitting in uikit `develop` [1.10.3].

We mightn’t get to do another release before the week is out, and it is technically a breaking change for us, since this would require edits in footer html template. We’ll likely do a new release early Jan.

See: https://github.com/AusDTO/gov-au-ui-kit/pull/453

**Comment by DJMyles** [comment]
No probs @klepas. Looking foward to seeing this alongside the callout changes I also had merged.

Love the updated guide as well - http://guides.service.gov.au/design-guide/ :)

**Comment by Feng-Shui** [comment]
@DJMyles has now been merged into master given we've pulled the UI Kit develop branch. Can this be closed now?

**Comment by DJMyles** [comment]
@Feng-Shui see https://github.com/govCMS/ui-kit-base-theme/pull/23 I still think this needs further discussion as per those comments on the PR independant of what it initially set out to do. I was satisfied it addressed the issue however there discussion about making this not menu specific which would require more thought / work.

The alternative is that we simply create a new issue for that.

**Comment by Feng-Shui** [comment]
@DJMyles see #38

**Comment by Feng-Shui** [comment]
Going to close this issue, it's old and we have a new PR to talk about these issues against.
