### ISSUE TITLE
UI Kit: Buttons

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/ui-kit-base-theme#3]
**As a site user
I want obvious and concise button styles
So I can perform actions and move through transactions.**

https://gov-au-ui-kit.apps.staging.digital.gov.au/section-buttons.html

---

We're going to need to do a bit of poking around to see how these styles mesh with the FAPI which makes use of `input type="submit/button"` - we may need to extend some of Drupal's styles via sass.  Also, need to look at how a few module's forms look:

- [x] Views front end UI 

- [x] Webform

- [x] SearchAPI and FacetAPI

- [x] Funnelback

- [x] Drupal login/user forms

- [x] govCMS consultation

**Comment by DJMyles** [comment]
Buttons are getting the ui kit style. any further customisation (inline input groups etc, positioning etc) can be done via sub theming.
