### ISSUE TITLE
UI KIT: global navigation

### ISSUE THREAD

**Issue by rujiali** [govCMS/ui-kit-base-theme#30]
**As a user
I want to place a global navigation menu block in a global navigation area.**

https://gov-au-ui-kit.apps.staging.digital.gov.au/section-navigation.html#guide-navigation-01-global-navigation

---

This is a sub issue of #19 , please refer to #19 for the scenario.

**Comment by rujiali** [comment]
Advice needed @Feng-Shui @DJMyles @mgdhs .
The UI KIT allows the 'logo' and 'tag' in the global navigation. See below:
<img width="480" alt="screen shot 2016-12-21 at 8 44 01 am" src="https://cloud.githubusercontent.com/assets/3487406/21369183/db25f546-c759-11e6-98c7-2a1a80caed64.png">
As we decide to add a new region for the global navigation, what do we display for the 'logo' and 'tag'? I can add the setting in our theme to allow user to input the text. What are your thoughts ?

**Comment by mgdhs** [comment]
@rujiali where does the global navigation go? Is it in the footer?

There is a discussion in the community at the moment about the [header](https://community.govcms.gov.au/t/design-discussion-page-header/494/3) since it isn't complete. Which means we can't progress much header stuff, even though it seems kind of important :|

**Comment by rujiali** [comment]
@mgdhs , we proposed the new region as the page top. So the section will be in header but render before the 'page-header' section. The discussion is in #19 . Example page: https://gov-au-ui-kit.apps.staging.digital.gov.au 

Happy to leave it postponed. Currently we don't have the scenario of this usage yet. The style is not hard to implement, we just need some business decision regarding the logo and tag.

**Comment by klepas** [comment]
Hey, just popping in to add some more context around this feature:

- it was designed for usage within the gov.au project, and may see removal in uikit 2.x (not yet confirmed)
- it is, to be quite honest, a rush implementation, and is missing a few things at the moment (cough hover and focus states…)
- it’s intended purpose was to allow users to navigate *up* and *above* the site they are currently in, not through that site itself — cf. [site navigation](http://guides.service.gov.au/design-guide/patterns/navigation/index.html#site-navigation), which is intended as the primary navigation for a given website (also note the lack of a global nav feature in the new guide)

With these things in mind I would probably recommend against implementing this feature for govcms at the moment.

Hit me up if I can help further. (:

**Comment by Feng-Shui** [comment]
Given that this is (tentatively) slated for removal in 2.x of the kit, and Health don't have a need for it, propose that we implement this in our sub-theme.

Thoughts?

**Comment by rujiali** [comment]
Agreed to implement it in subtheme. 

Close the issue now.
