### ISSUE TITLE
Drupal: create layout in Display Suite for horizontal list

### ISSUE THREAD

**Issue by rujiali** [govCMS/ui-kit-base-theme#33]
**As an administrator
I want to be able to use UI KIT horizontal list as a display suite layout.**

http://guides.service.gov.au/design-guide/components/list-styles/index.html#horizontal-style

---

Creating a custom layout following the steps in [https://www.drupal.org/node/1098068](https://www.drupal.org/node/1098068). Add horizontal HTML tags in the LAYOUT.tpl.php file.

**Comment by rujiali** [comment]
Can do it from display suite settings to change the tag to figure or article.

**Comment by rujiali** [comment]
Still need a custom template to remove the wrapper.

**Comment by Feng-Shui** [comment]
@rujiali can you use the `Expert` (I think it is) formatting options to nuke the wrapper?

**Comment by rujiali** [comment]
Do I need any module enabled to see `expert` option ? @Feng-Shui

**Comment by Feng-Shui** [comment]
Yep Display Suite Extras

**Comment by Feng-Shui** [comment]
It might just give you field level wrappers, can't remember.

**Comment by rujiali** [comment]
ok, find it now. It is about field template which can not help us. Drupal by default has a wrapper for all the fields, which is the one we want to nuke. We can either do it from a custom 2 cols ds template or custom layout. I'd prefer to use a custom layout than overriding the default template.

**Comment by rujiali** [comment]
#37

**Comment by Feng-Shui** [comment]
PR merged
