### ISSUE TITLE
Search placeholders are bad for usability

### ISSUE THREAD

**Issue by mgdhs** [govCMS/ui-kit-base-theme#55]
Nielsen Norman Group [says](https://www.nngroup.com/articles/form-design-placeholders/):

> 5. Fields with stuff in them are less noticeable. [...] Eyetracking studies show that users’ **eyes are drawn to empty fields**.

I agree they can be nice and useful sometimes. Our implementation is however awkward. The Drupal default says 'Type search here', duh, but the button also says 'search'. It seems unneccessary.

<img width="384" alt="screen shot 2017-01-20 at 15 36 00" src="https://cloud.githubusercontent.com/assets/13895751/22136084/5865c6ce-df26-11e6-86a2-a890f42a19f5.png">

We've also had usability reports on our our main site and other sites with recommendations to remove it. Google and Bing also have empty placeholders. [Some more evidence from a blog](https://www.digitalgov.gov/2014/11/24/placeholder-text-think-outside-the-box/). The [DTA Design Guide](http://guides.service.gov.au/design-guide/components/forms-buttons/index.html) also doesn't have placeholder text and instead uses hints on more complex form fields.

**Comment by Feng-Shui** [comment]
@mgdhs do you want to tag some specific people here to get some input on this?  It would simplify a few things if I could just remove it completely.

**Comment by Feng-Shui** [comment]
*Note: grey border around Search button has been fixed, because someone will point that out :p

**Comment by Podgkin** [comment]
I just conferred with our services designer, and the research we have seen agrees with @mgdhs

**Comment by Feng-Shui** [comment]
Will action this afternoon.

**Comment by Feng-Shui** [comment]
PR #59

**Comment by DJMyles** [comment]
@Feng-Shui your changes are good, all working. I used this branch to fix a slight alignment issue of the input group in mobile. Can you review for me.

**Comment by Feng-Shui** [comment]
#59

**Comment by mgdhs** [comment]
Yay, it is nice when that happens @Podgkin :)
