### ISSUE TITLE
Drupal: theme settings for sidebar

### ISSUE THREAD

**Issue by rujiali** [govCMS/ui-kit-base-theme#6]
**As a site admin
I want to be able to set the sidebar's position from the theme setting form.**

https://gov-au-ui-kit.apps.staging.digital.gov.au/section-grid.html#guide-grid-6-sidebar

---

The UI KIT is positioning the sidebar right/left according to the class name 'sidebar-has-controls' in the parent of the sidebar section. We need to alter the theme settings form in theme-setting.php to allow user to choose which side the sidebar is rendered. And use the value to add the class name to the sidebar accordingly in the preprocess function.

**Comment by rujiali** [comment]
Do we even want to allow the user to choose which page they would like to put the sidebar to left by url ? @Feng-Shui

**Comment by Feng-Shui** [comment]
Yeah, I'm thinking my way through this at the moment.  Does the grid allow for two sidebars (left and right), plus content?

**Comment by rujiali** [comment]
Don't think the UI-KIT supports the right and left sidebars out of box, need custom style for it.

**Comment by Feng-Shui** [comment]
I think that a theme setting for left/right placement makes sense.  Our preference would be to roll with a left hand column by default.  That work for you guys?

**Comment by rujiali** [comment]
@Feng-Shui, we are using the right column as the default. :) But this should not be a problem if we have the global setting. With that said, I would propose to use the UI KIT default (right column) as the default as the UI KIT is doing so. 
Do we allow user to specify the urls with wildcard where they would like to put the sidebar not in default region ?

**Comment by Feng-Shui** [comment]
:) Happy to run with a RHC default given that's what the kit defaults to.  For MPV, let's not worry about switching left/right based on path for now.  If you always use right, and we always use left, let's roll with that.

**Comment by rujiali** [comment]
PR ready for review. #9
