### ISSUE TITLE
Open Sans font

### ISSUE THREAD

**Issue by mgdhs** [govCMS/ui-kit-base-theme#61]
The [UI toolkit body font](http://guides.service.gov.au/design-guide/foundations/typography/index.html) is `"Open Sans", Verdana, "Bitstream Vera Sans", sans-serif`.

[Open Sans](https://en.wikipedia.org/wiki/Open_Sans) is not bundled with *any* devices, which means it is defaulting back to Verdana. The UI toolkit site specifically includes it from Google Fonts.

The base theme is currently missing out on this font. We'll need to do something to make it work.

**Comment by Feng-Shui** [comment]
Merged
