### ISSUE TITLE
Full with pages without the need to sub-theme

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/ui-kit-base-theme#69]
```
@media screen and (min-width: 75em)

main .content-main:first-child {
    ...
    margin-right: 2.04556%;
    width: 61.73292%;
}
```

The above rule causes issues when a layout should be full width.  I can see that you guys are targeting specific node type classes on the body element to do this on your campaigns site:

```
@media screen and (min-width: 420px)
.node-type-campaign main .content-main {
    ...
    margin-right: 4.17655%;
    width: 100%;
}
```

We're going to need a way to resolve this in the base theme.  I've had a bit of a think about this and I'd like to propose the following:

1. For each of the main ways content is displayed (Panel pages, Views, and Nodes/DS) we provide body classes to identify each:
    1. Panels pages: `page-[name] page-[name]-[variant]`
    1. Views: `views-[name] views-[name]-[display]`
    1. Nodes/DS: `node node-[type] node-[nid] node-[view-mode]`
1. Make a new theme setting that allows any of the above classes to be listed
1. When the class is matched, and the `no-sidebars` class is also on the body, the width is set to full.

This would allow full width pages to be set via UI without the need to sub-theme.

By default, we'd provide some sensible defaults:

```
.no-sidebars.front
.no-sidebars.panels
```

**Comment by Feng-Shui** [comment]
@rujiali @dlm78 thoughts on the above? I'm going to get the code together to see if this is viable.

**Comment by rujiali** [comment]
Thanks @Feng-Shui . The proposed solution makes sense to me. Do we allow user to type the classes in a text area I suppose ?

**Comment by Feng-Shui** [comment]
Yeah, I think so...

I was contemplating making it a form UI, so you could pick the Panels, Views, node view modes etc by name, but that's potentially a LOT of options.

Initially, I'll implement it as a textarea, we can look at the above if it works nicely.  Would prob need something like Chosen to make it manageable - not sure what we have in the profile.

**Comment by rujiali** [comment]
Yeah, it would open a big world. Select list makes too hard to include every option. I vote for the text area.
