### ISSUE TITLE
node_modules folder can cause WSOD

### ISSUE THREAD

**Issue by Feng-Shui** [govCMS/ui-kit-base-theme#78]
We've run into the following issue: https://www.drupal.org/node/2482549

Specifically when using Context Add Assets module, although it's simply calling `file_scan_directory()` which other modules will do.

This is likely going to be an issue on development environments, at `node_modules` should not exist in production, but if this theme is adopted in govCMS, we might need to look at the core patch in that issue.  It's been patched in D8, this is a backport patch.

**Comment by mgdhs** [comment]
A Drupal core problem.
